// examples/react/src/App.tsx
import React, { useRef } from 'react';
import { IKVideoPlayer } from '@imagekit/video-player/react';
import type {
    IKVideoPlayerRef,
    IKPlayerOptions,
    SourceOptions,
    PlaylistOptions
} from '@imagekit/video-player/react';

import '@imagekit/video-player/dist/styles.css';

export default function App() {
    const playerRef = useRef<IKVideoPlayerRef>(null);

    // 1) Define your ImageKit IKPlayerOptions
    const ikOptions: IKPlayerOptions = {
        imagekitId: 'YOUR_IMAGEKIT_ID',
        seekThumbnails: true,
        logo: {
            showLogo: true,
            logoImageUrl: 'https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg',
            logoOnclickUrl: 'https://imagekit.io/',
        },
    };

    // 2) For a single video source (SourceOptions)
    const singleSource: SourceOptions = {
        src: 'https://ik.imagekit.io/zuqlyov9d/SEO-friendly%20file%20names.mp4',
        transformation: [
            { width: 400, height: 400 },
        ],
        chapters: true,
        info: { title: 'Dog', subtitle: 'Dog wearing cap', description: 'This is a video containing dog wearing cap.' }
    };

    // 3) (alternative) for a playlist of videos
    const playlist: {
        sources: SourceOptions[];
        options?: PlaylistOptions;
    } = {
        sources: [
            {
                src: 'https://ik.imagekit.io/zuqlyov9d/SEO-friendly%20file%20names.mp4',
                transformation: [
                    { width: 400, height: 400 },
                ],
                chapters: true,
                info: { title: 'Dog', subtitle: 'Dog wearing cap', description: 'This is a video containing dog wearing cap.' }
            },
            {
                src: 'https://ik.imagekit.io/zuqlyov9d/example_video_2.mp4',
                transformation: [
                    { width: 400, height: 400 },
                ],
                chapters: true,
                info: { title: 'Human', subtitle: 'Human lying in grass', description: 'This is a video showing human lying on the grass. He is smiling.' },
                textTracks: [
                    {
                        autoGenerate: true,
                        maxWordsPerLine: 4,
                        highlightWords: true,
                        default: true // Indicates whether this track is active by default
                    }]
            },
            {
                src: 'https://ik.imagekit.io/zuqlyov9d/sample-video.mp4',
                chapters: true,
                info: { title: 'Bird', subtitle: 'Bird on a branch', description: 'This video depicts bird chirping. It is sitting on a tree branch.' },
            },
        ], options: {
            autoAdvance: 1,
            repeat: true,
            presentUpcoming: 10,
            widgetProps: { direction: 'vertical' }
        }
    };

    return (
        <div>
            <IKVideoPlayer
                ref={playerRef}
                ikOptions={ikOptions}
                videoJsOptions={{
                    controls: true,
                    muted: false,
                    height: 540,
                    width: 960,
                }}
                playlist={playlist}
            />
        </div>

    );
}

// examples/angular/src/app/app.component.ts
// src/app/app.component.ts

import { Component, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common'; // <-- Import CommonModule for ngStyle
import { IkVideoPlayerComponent } from '@imagekit/video-player/angular';
import type { PlayerOptions, SourceOptions, PlaylistOptions } from '@imagekit/video-player';
// import type Player from 'video.js/dist/types/player';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  standalone: true, // <-- 1. Mark AppComponent as standalone
  imports: [
    CommonModule, // <-- 2. Import CommonModule for ngStyle
    IkVideoPlayerComponent, // <-- 3. Import your player component directly here
  ],
})
export class AppComponent {
  // Use @ViewChild to get a reference to our component instance in the template.
  // This is the Angular equivalent of React's `useRef` for component instances.
  @ViewChild(IkVideoPlayerComponent) playerComponent?: IkVideoPlayerComponent;

  // Define component properties for player options and sources
  ikOptions: PlayerOptions = {
    imagekitId: 'YOUR_IMAGEKIT_ID', // Remember to replace this
    seekThumbnails: true,
    logo: {
      showLogo: true,
      logoImageUrl: 'https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg',
      logoOnclickUrl: 'https://imagekit.io/',
    },
  };

  playlist: {
    sources: SourceOptions[];
    options?: PlaylistOptions;
  } = {
    sources: [
      {
        src: 'https://ik.imagekit.io/zuqlyov9d/SEO-friendly%20file%20names.mp4',
        info: { title: 'Dog', subtitle: 'Dog wearing cap', description: 'This is a video containing dog wearing cap.' }
      },
      {
        src: 'https://ik.imagekit.io/zuqlyov9d/example_video_2.mp4',
        info: { title: 'Human', subtitle: 'Human lying in grass', description: 'This is a video showing human lying on the grass.' },
      },
      {
        src: 'https://ik.imagekit.io/zuqlyov9d/sample-video.mp4',
        info: { title: 'Bird', subtitle: 'Bird on a branch', description: 'This video depicts bird chirping.' },
      },
    ],
    options: {
      autoAdvance: 5,
      repeat: true,
      presentUpcoming: 10,
    }
  };

  // Define styles as an object for [ngStyle]
  playerStyles = {
    width: '100%'
  };
}
<div style="max-width: 800px; margin: 2rem auto;">
    <h1>ImageKit Video Player (Angular) Example</h1>
    <div style="margin-top: 1rem;">
      <ik-video-player
        [ikOptions]="ikOptions"
        [videoJsOptions]="{
          controls: true,
          fluid: true,
          muted: false
        }"
        [playlist]="playlist"
        [className]="'my-custom-player-container'"
        [ngStyle]="playerStyles"
      ></ik-video-player>
    </div>
  </div>
