// examples/vue/src/App.vue
<template>
  <div class="container">
    <h1>ImageKit Video Player (Vue) Example</h1>
    <div>
      <IKVideoPlayer ref="playerRef" :ikOptions="ikOptions" :videoJsOptions="{
        controls: true,
        muted: false,
        height: 540,
        width: 960,
      }" :playlist="playlist" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { IKVideoPlayer } from '@imagekit/video-player/vue';
import type { IKPlayerOptions, SourceOptions, PlaylistOptions, IKVideoPlayerRef, InteractionProps } from '@imagekit/video-player/vue';

const playerRef = ref<IKVideoPlayerRef | null>(null);

const ikOptions: IKPlayerOptions = {
  imagekitId: 'YOUR_IMAGEKIT_ID', // Remember to replace this
  seekThumbnails: true,
  analytics: {
    enabled: true,
    userId: 'test_user_id',
  },
};

const playlist: {
  sources: SourceOptions[];
  options?: PlaylistOptions;
} = {
  sources: [
    {
      src: "https://ik.imagekit.io/ikmedia/docs/video-player/playlist/horses.mp4",
      info: { title: "Horses Running", description: "Horses grazing in the field" },
      // Chapters: Auto-generate chapters
      chapters: true,
      // Subtitles: Auto-generated with translations
      textTracks: [
        {
          autoGenerate: true,
          maxChars: 60,
          highlightWords: true,
        },
        {
          autoGenerate: true,
          showAutoGenerated: false,
          translations: [
            {
              langCode: "hi",
              label: "Hindi (AI)",
            },
            {
              langCode: "de",
              label: "German (AI)",
            },
          ],
        },
      ],
    },
    {
      src: "https://ik.imagekit.io/ikmedia/docs/video-player/playlist/lion.mp4",
      info: {
        title: "Lion",
        description: "Lion roaming in the wild",
      },
      // Chapters: Auto-generate chapters
      chapters: true,
      // Subtitles: Auto-generated with translations
      textTracks: [
        {
          autoGenerate: true,
          maxChars: 60,
          highlightWords: true,
        },
        {
          autoGenerate: true,
          showAutoGenerated: false,
          translations: [
            {
              langCode: "hi",
              label: "Hindi (AI)",
            },
            {
              langCode: "de",
              label: "German (AI)",
            },
          ],
        },
      ],
      // Shoppable: Products with hotspots
      shoppable: {
        products: [
          {
            productId: 1,
            productName: "Wildlife Photography Gear",
            highlightTime: { start: 2, end: 6 },
            imageUrl: "https://ik.imagekit.io/ikmedia/docs/video-player/shoppable/aviators.jpeg",
            hotspots: [
              {
                time: "00:05",
                x: "50%",
                y: "40%",
                tooltipPosition: "right",
                clickUrl: "https://www.example.com/wildlife-gear"
              }
            ],
            onHover: {
              action: "overlay",
              args: "Click to see wildlife photography gear"
            } as InteractionProps,
            onClick: {
              action: "goto",
              pause: true,
              args: {
                url: "https://www.example.com/wildlife-gear"
              }
            }
          }
        ],
        showPostPlayOverlay: true,
        autoClose: false,
        startState: "openOnPlay"
      },
    },
    {
      src: "https://ik.imagekit.io/ikmedia/docs/video-player/playlist/dog_running.mp4",
      info: { title: "Dog Running" },
      // Chapters: Auto-generate chapters
      chapters: true,
      // Subtitles: Auto-generated
      textTracks: [
        {
          autoGenerate: true,
          maxChars: 60,
          highlightWords: true,
        },
      ],
    },
    {
      src: "https://ik.imagekit.io/ikmedia/docs/video-player/playlist/man_smiling.mp4",
      info: {
        title: "Man Smiling",
        description: "Man smiling at the camera",
      },
      // Chapters: Auto-generate chapters
      chapters: true,
      // Subtitles: Auto-generated with translations
      textTracks: [
        {
          autoGenerate: true,
          maxChars: 60,
          highlightWords: true,
        },
        {
          autoGenerate: true,
          showAutoGenerated: false,
          translations: [
            {
              langCode: "hi",
              label: "Hindi (AI)",
            },
          ],
        },
      ],
      // Shoppable: Products
      shoppable: {
        products: [
          {
            productId: 1,
            productName: "Camera Equipment",
            imageUrl: "https://ik.imagekit.io/ikmedia/docs/video-player/shoppable/wooden_frames.jpeg",
            onHover: {
              action: "overlay",
              args: "Click to see camera equipment"
            } as InteractionProps,
            onClick: {
              action: "goto",
              pause: true,
              args: {
                url: "https://www.example.com/camera-equipment"
              }
            }
          }
        ],
        showPostPlayOverlay: true,
        autoClose: false,
        startState: "openOnPlay"
      },
    },
    {
      src: "https://ik.imagekit.io/ikmedia/docs/video-player/playlist/rhino.mp4",
      info: { title: "Rhino at the zoo" },
      // Chapters: Auto-generate chapters
      chapters: true,
      // Subtitles: Auto-generated
      textTracks: [
        {
          autoGenerate: true,
          maxChars: 60,
          highlightWords: true,
        },
      ],
    },
    {
      src: "https://ik.imagekit.io/demo/sample-video.mp4",
      info: { title: "Bird on branch" },
      // Chapters: Auto-generate chapters
      chapters: true,
      // Subtitles: Auto-generated with translations
      textTracks: [
        {
          autoGenerate: true,
          maxChars: 60,
          highlightWords: true,
        },
        {
          autoGenerate: true,
          showAutoGenerated: false,
          translations: [
            {
              langCode: "hi",
              label: "Hindi (AI)",
            },
            {
              langCode: "de",
              label: "German (AI)",
            },
          ],
        },
      ],
    },
    {
      src: "https://ik.imagekit.io/ikmedia/docs/video-player/shoppable/video.mp4",
      info: { title: "Shoppable Video", description: "Full-featured shoppable video with multiple products" },
      // Shoppable: Full product configuration from JavaScript example
      shoppable: {
        products: [
          {
            productId: 1,
            productName: "Classic Aviators",
            highlightTime: { start: 2, end: 6 },
            imageUrl: "https://ik.imagekit.io/ikmedia/docs/video-player/shoppable/aviators.jpeg",
            hotspots: [
              {
                time: "00:06",
                x: "48%",
                y: "35%",
                tooltipPosition: "left",
                clickUrl: "https://images.pexels.com/photos/701877/pexels-photo-701877.jpeg"
              }
            ],
            onHover: {
              action: "overlay",
              args: "Click to see this product in the video"
            } as InteractionProps,
            onClick: {
              action: "seek",
              pause: 5,
              args: { time: "00:06" }
            }
          },
          {
            productId: 2,
            productName: "Wooden frame glasses",
            imageUrl: "https://ik.imagekit.io/ikmedia/docs/video-player/shoppable/wooden_frames.jpeg",
            onHover: {
              action: "switch",
              args: {
                url: "https://ik.imagekit.io/ikmedia/docs/video-player/shoppable/wooden_frames.jpeg"
              }
            },
            onClick: {
              action: "goto",
              pause: true,
              args: {
                url: "https://www.pexels.com/search/wooden%20glasses%20frames/"
              }
            }
          },
          {
            productId: 3,
            productName: "Sunglasses",
            imageUrl: "https://ik.imagekit.io/ikmedia/docs/video-player/shoppable/sunglass.jpeg",
            onHover: {
              action: "overlay",
              args: "Click to go to website"
            } as InteractionProps,
            onClick: {
              action: "goto",
              pause: true,
              args: {
                url: "https://www.pexels.com/photo/red-lens-sunglasses-on-sand-near-sea-at-sunset-selective-focus-photography-46710/"
              }
            }
          },
          {
            productId: 4,
            productName: "Eye protection",
            highlightTime: { start: 7, end: 9 },
            imageUrl: "https://ik.imagekit.io/ikmedia/docs/video-player/shoppable/protection.jpeg",
            onClick: {
              action: "goto",
              pause: true,
              args: {
                url: "https://www.pexels.com/photo/red-lens-sunglasses-on-sand-near-sea-at-sunset-selective-focus-photography-46710/"
              }
            }
          }
        ],
        showPostPlayOverlay: true,
        autoClose: false,
        startState: "open"
      }
    },
    {
      src: "https://ik.imagekit.io/ikmedia/docs/video-player/subtitle_chapter/demo.mp4",
      info: { title: "Chapters & Subtitles Demo", description: "Video with AI-generated chapters and subtitles" },
      // Chapters: Auto-generate chapters
      chapters: true,
      // Subtitles: Auto-generated with translations
      textTracks: [
        {
          autoGenerate: true,
          translations: [
            {
              langCode: "hi",
              label: "Hindi (AI)",
              default: true,
            },
            {
              langCode: "de",
              label: "German (AI)",
            },
          ],
        }
      ],
    }
  ],
  options: { autoAdvance: 5 }, // Set autoAdvance to a valid number (e.g., 5 seconds)
};

// Example: Access the player instance and use it
onMounted(() => {
  // Wait a bit for the player to initialize
  setTimeout(() => {
    const player = playerRef.value?.getPlayer();
    if (player) {
      // Example: Listen to player events
      player.on('play', () => {
        console.log('Video started playing');
      });

      player.on('pause', () => {
        console.log('Video paused');
      });

      // Example: Access playlist manager (if playlist is already set via props)
      // Note: playlist() method requires options, so we access it via the plugin
      const plugin = player.imagekitVideoPlayer();
      if (plugin) {
        const playlistManager = plugin.getPlaylistManager();
        if (playlistManager) {
          console.log('Playlist manager available:', playlistManager);
        }

        const currentSource = plugin.getOriginalCurrentSource();
        console.log('Current source:', currentSource);
      }
    }
  }, 1000);
});
</script>

<style>
/* Global import for video-js styles */
@import '@imagekit/video-player/styles.css';
</style>

// examples/react/src/App.tsx
import React, { useRef } from 'react';
import { IKVideoPlayer } from '@imagekit/video-player/react';
import type {
    IKVideoPlayerRef,
    IKPlayerOptions,
    SourceOptions,
    PlaylistOptions
} from '@imagekit/video-player/react';

import '@imagekit/video-player/styles.css';

export default function App() {
    const playerRef = useRef<IKVideoPlayerRef>(null);

    // 1) Define your ImageKit IKPlayerOptions
    const ikOptions: IKPlayerOptions = {
        imagekitId: 'YOUR_IMAGEKIT_ID',
        seekThumbnails: true,
        logo: {
            showLogo: true,
            logoImageUrl: 'https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg',
            logoOnclickUrl: 'https://imagekit.io/',
        },
        analytics: {
            enabled: true,
            userId: 'test_user_id',
        },
    };

    // 2) For a single video source (SourceOptions)
    const singleSource: SourceOptions = {
        src: 'https://ik.imagekit.io/demo/sample-video.mp4',
        transformation: [
            { width: 400, height: 400 },
        ],
        chapters: true,
        info: { title: 'Bird on branch', description: 'This is a video containing bird on a branch.' }
    };

    // 3) (alternative) for a playlist of videos with ALL features enabled
    const playlist: {
        sources: SourceOptions[];
        options?: PlaylistOptions;
    } = {
        sources: [
            {
              src: "https://ik.imagekit.io/ikmedia/docs/video-player/playlist/horses.mp4",
              info: { title: "Horses Running", description: "Horses grazing in the field" },
              // Chapters: Auto-generate chapters
              chapters: true,
              // Subtitles: Auto-generated with translations
              textTracks: [
                {
                  autoGenerate: true,
                  maxChars: 60,
                  highlightWords: true,
                },
                {
                  autoGenerate: true,
                  showAutoGenerated: false,
                  translations: [
                    {
                      langCode: "hi",
                      label: "Hindi (AI)",
                    },
                    {
                      langCode: "de",
                      label: "German (AI)",
                    },
                  ],
                },
              ],
            },
            {
              src: "https://ik.imagekit.io/ikmedia/docs/video-player/playlist/lion.mp4",
              info: {
                title: "Lion",
                description: "Lion roaming in the wild",
              },
              // Chapters: Auto-generate chapters
              chapters: true,
              // Subtitles: Auto-generated with translations
              textTracks: [
                {
                  autoGenerate: true,
                  maxChars: 60,
                  highlightWords: true,
                },
                {
                  autoGenerate: true,
                  showAutoGenerated: false,
                  translations: [
                    {
                      langCode: "hi",
                      label: "Hindi (AI)",
                    },
                    {
                      langCode: "de",
                      label: "German (AI)",
                    },
                  ],
                },
              ],
              // Shoppable: Products with hotspots
              shoppable: {
                products: [
                  {
                    productId: 1,
                    productName: "Wildlife Photography Gear",
                    highlightTime: { start: 2, end: 6 },
                    imageUrl: "https://ik.imagekit.io/ikmedia/docs/video-player/shoppable/aviators.jpeg",
                    hotspots: [
                      {
                        time: "00:05",
                        x: "50%",
                        y: "40%",
                        tooltipPosition: "right",
                        clickUrl: "https://www.example.com/wildlife-gear"
                      }
                    ],
                    onHover: {
                      action: "overlay",
                      args: "Click to see wildlife photography gear"
                    },
                    onClick: {
                      action: "goto",
                      pause: true,
                      args: {
                        url: "https://www.example.com/wildlife-gear"
                      }
                    }
                  }
                ],
                showPostPlayOverlay: true,
                autoClose: false,
                startState: "openOnPlay"
              },
            },
            {
              src: "https://ik.imagekit.io/ikmedia/docs/video-player/playlist/dog_running.mp4",
              info: { title: "Dog Running" },
              // Chapters: Auto-generate chapters
              chapters: true,
              // Subtitles: Auto-generated
              textTracks: [
                {
                  autoGenerate: true,
                  maxChars: 60,
                  highlightWords: true,
                },
              ],
            },
            {
              src: "https://ik.imagekit.io/ikmedia/docs/video-player/playlist/man_smiling.mp4",
              info: {
                title: "Man Smiling",
                description: "Man smiling at the camera",
              },
              // Chapters: Auto-generate chapters
              chapters: true,
              // Subtitles: Auto-generated with translations
              textTracks: [
                {
                  autoGenerate: true,
                  maxChars: 60,
                  highlightWords: true,
                },
                {
                  autoGenerate: true,
                  showAutoGenerated: false,
                  translations: [
                    {
                      langCode: "hi",
                      label: "Hindi (AI)",
                    },
                  ],
                },
              ],
              // Shoppable: Products
              shoppable: {
                products: [
                  {
                    productId: 1,
                    productName: "Camera Equipment",
                    imageUrl: "https://ik.imagekit.io/ikmedia/docs/video-player/shoppable/wooden_frames.jpeg",
                    onHover: {
                      action: "overlay",
                      args: "Click to see camera equipment"
                    },
                    onClick: {
                      action: "goto",
                      pause: true,
                      args: {
                        url: "https://www.example.com/camera-equipment"
                      }
                    }
                  }
                ],
                showPostPlayOverlay: true,
                autoClose: false,
                startState: "openOnPlay"
              },
            },
            {
              src: "https://ik.imagekit.io/ikmedia/docs/video-player/playlist/rhino.mp4",
              info: { title: "Rhino at the zoo"},
              // Chapters: Auto-generate chapters
              chapters: true,
              // Subtitles: Auto-generated
              textTracks: [
                {
                  autoGenerate: true,
                  maxChars: 60,
                  highlightWords: true,
                },
              ],
            },
            {
              src: "https://ik.imagekit.io/demo/sample-video.mp4",
              info: { title: "Bird on branch"},
              // Chapters: Auto-generate chapters
              chapters: true,
              // Subtitles: Auto-generated with translations
              textTracks: [
                {
                  autoGenerate: true,
                  maxChars: 60,
                  highlightWords: true,
                },
                {
                  autoGenerate: true,
                  showAutoGenerated: false,
                  translations: [
                    {
                      langCode: "hi",
                      label: "Hindi (AI)",
                    },
                    {
                      langCode: "de",
                      label: "German (AI)",
                    },
                  ],
                },
              ],
            },
            {
              src: "https://ik.imagekit.io/ikmedia/docs/video-player/shoppable/video.mp4",
              info: { title: "Shoppable Video", description: "Full-featured shoppable video with multiple products" },
              // Shoppable: Full product configuration from JavaScript example
              shoppable: {
                products: [
                  {
                    productId: 1,
                    productName: "Classic Aviators",
                    highlightTime: { start: 2, end: 6 },
                    imageUrl: "https://ik.imagekit.io/ikmedia/docs/video-player/shoppable/aviators.jpeg",
                    hotspots: [
                      {
                        time: "00:06",
                        x: "48%",
                        y: "35%",
                        tooltipPosition: "left",
                        clickUrl: "https://images.pexels.com/photos/701877/pexels-photo-701877.jpeg"
                      }
                    ],
                    onHover: {
                      action: "overlay",
                      args: "Click to see this product in the video"
                    },
                    onClick: {
                      action: "seek",
                      pause: 5,
                      args: { time: "00:06" }
                    }
                  },
                  {
                    productId: 2,
                    productName: "Wooden frame glasses",
                    imageUrl: "https://ik.imagekit.io/ikmedia/docs/video-player/shoppable/wooden_frames.jpeg",
                    onHover: {
                      action: "switch",
                      args: {
                        url: "https://ik.imagekit.io/ikmedia/docs/video-player/shoppable/wooden_frames.jpeg"
                      }
                    },
                    onClick: {
                      action: "goto",
                      pause: true,
                      args: {
                        url: "https://www.pexels.com/search/wooden%20glasses%20frames/"
                      }
                    }
                  },
                  {
                    productId: 3,
                    productName: "Sunglasses",
                    imageUrl: "https://ik.imagekit.io/ikmedia/docs/video-player/shoppable/sunglass.jpeg",
                    onHover: {
                      action: "overlay",
                      args: "Click to go to website"
                    },
                    onClick: {
                      action: "goto",
                      pause: true,
                      args: {
                        url: "https://www.pexels.com/photo/red-lens-sunglasses-on-sand-near-sea-at-sunset-selective-focus-photography-46710/"
                      }
                    }
                  },
                  {
                    productId: 4,
                    productName: "Eye protection",
                    highlightTime: { start: 7, end: 9 },
                    imageUrl: "https://ik.imagekit.io/ikmedia/docs/video-player/shoppable/protection.jpeg",
                    onClick: {
                      action: "goto",
                      pause: true,
                      args: {
                        url: "https://www.pexels.com/photo/red-lens-sunglasses-on-sand-near-sea-at-sunset-selective-focus-photography-46710/"
                      }
                    }
                  }
                ],
                showPostPlayOverlay: true,
                autoClose: false,
                startState: "open"
              }
            },
            {
              src: "https://ik.imagekit.io/ikmedia/docs/video-player/subtitle_chapter/demo.mp4",
              info: { title: "Chapters & Subtitles Demo", description: "Video with AI-generated chapters and subtitles" },
              // Chapters: Auto-generate chapters
              chapters: true,
              // Subtitles: Auto-generated with translations
              textTracks: [
                {
                  autoGenerate: true,
                  translations: [
                    {
                      langCode: "hi",
                      label: "Hindi (AI)",
                      default: true,
                    },
                    {
                      langCode: "de",
                      label: "German (AI)",
                    },
                  ],
                }
              ],
            }
          ], options: {
            autoAdvance: 1,
            repeat: true,
            presentUpcoming: 10,
            widgetProps: { direction: 'vertical' }
        }
    };

    return (
        <div>
            <IKVideoPlayer
                ref={playerRef}
                ikOptions={ikOptions}
                videoJsOptions={{
                    controls: true,
                    muted: false,
                    height: 540,
                    width: 960,
                }}
                playlist={playlist}
            />
        </div>

    );
}
