// packages/video-player/react-wrapper/IKVideoPlayer.tsx
import {
  useRef,
  useEffect,
  forwardRef,
  useImperativeHandle,
} from 'react';
import { videoPlayer } from '../javascript';

import type { IKVideoPlayerProps, IKVideoPlayerRef } from './interfaces';
import React from 'react';

const IKVideoPlayer = forwardRef<IKVideoPlayerRef, IKVideoPlayerProps>(
  (
    { ikOptions, videoJsOptions = {}, source, playlist },
    ref
  ) => {
    // A ref to the actual <video> element
    const videoRef = useRef<HTMLVideoElement | null>(null);
    // A ref to hold the Video.js player instance once initialized
    const playerRef = useRef<any | null>(null);

    // Expose getPlayer() to parent components
    useImperativeHandle(ref, () => ({
      getPlayer: () => playerRef.current,
    }));

    useEffect(() => {
      // If there was already a player, dispose it before re-creating
      if (playerRef.current) {
        playerRef.current.dispose();
        playerRef.current = null;
      }

      // Ensure our <video> DOM node is present
      if (!videoRef.current) return;

      // Initialize Video.js via the helper from '@imagekit/video-player'
      const playerInstance = videoPlayer(
        videoRef.current,
        ikOptions,
        videoJsOptions
      );
      playerRef.current = playerInstance;

      // If both source and playlist are provided, warn and pick playlist
      if (source && playlist) {
        console.warn(
          '[IKVideoPlayer] Both `source` and `playlist` were provided. Using `playlist`.'
        );
      }

      // Apply playlist if given
      if (
        playlist &&
        Array.isArray(playlist.sources) &&
        playlist.sources.length > 0
      ) {
        const playlistMgr = playerInstance.playlist({
          sources: playlist.sources,
          options: playlist.options || {},
        });
        playlistMgr.loadFirstItem();
      } else if (source) {
        // Otherwise, set a single source
        playerInstance.src(source);
      }

      // Clean up when component unmounts
      return () => {
        if (playerRef.current) {
          playerRef.current.dispose();
          playerRef.current = null;
        }
      };
      // We intentionally do not re-run on `source` or `playlist` changes
      // If you need runtime updates, add a separate effect for that.
    }, [ikOptions, videoJsOptions]);

    return (
      <video
        ref={videoRef}
        className={`video-js vjs-default-skin`}
        controls
        preload="auto"
      />
    );
  }
);

export default IKVideoPlayer;

// packages/video-player/angular/ik-video-player.component.ts
import {
    Component,
    Input,
    ViewChild,
    ElementRef,
    OnChanges,
    OnDestroy,
    SimpleChanges,
  } from '@angular/core';
  import { CommonModule } from '@angular/common'; // <-- 1. IMPORT CommonModule
  import { videoPlayer } from '../javascript';
  import type { IKVideoPlayerProps } from './interfaces';
  import type Player from 'video.js/dist/types/player';
  
  @Component({
    selector: 'ik-video-player',
    templateUrl: './ik-video-player.component.html',
    standalone: true, // <-- 2. ADD this line
    imports: [CommonModule], // <-- 3. ADD this line
  })
  export class IkVideoPlayerComponent implements OnChanges, OnDestroy {
    @Input() ikOptions!: IKVideoPlayerProps['ikOptions'];
    @Input() videoJsOptions: IKVideoPlayerProps['videoJsOptions'] = {};
    @Input() source?: IKVideoPlayerProps['source'];
    @Input() playlist?: IKVideoPlayerProps['playlist'];
    @Input() className?: IKVideoPlayerProps['className'];
    @Input() style?: IKVideoPlayerProps['style'];
  
    // Get a reference to the <video> element from the template
    @ViewChild('videoPlayerElement', { static: true })
    videoElement!: ElementRef<HTMLVideoElement>;
  
    private player?: Player;
  
    // This lifecycle hook runs whenever an @Input() property changes.
    // It's the equivalent of React's useEffect with a dependency array.
    ngOnChanges(changes: SimpleChanges): void {
      // We only want to re-initialize the player if the core options change,
      // just like in the React wrapper.
      if (changes['ikOptions'] || changes['videoJsOptions']) {
        this.initializePlayer();
      }
    }
  
    private initializePlayer(): void {
      // Dispose the old player instance if it exists, to prevent memory leaks
      if (this.player) {
        this.player.dispose();
      }
  
      if (!this.videoElement?.nativeElement) return;
  
      // Initialize the player
      this.player = videoPlayer(
        this.videoElement.nativeElement,
        this.ikOptions,
        this.videoJsOptions
      );
  
      // If both source and playlist are provided, warn and pick playlist
      if (this.source && this.playlist) {
        console.warn(
          '[IKVideoPlayer] Both `source` and `playlist` were provided. Using `playlist`.'
        );
      }
  
      // Apply playlist or source
      if (this.playlist && Array.isArray(this.playlist.sources) && this.playlist.sources.length > 0) {
        const playlistMgr = (this.player as any).playlist({
          sources: this.playlist.sources,
          options: this.playlist.options || {},
        });
        playlistMgr.loadFirstItem();
      } else if (this.source) {
        this.player.src(this.source);
      }
  
    }
  
    // This is the public method that parent components can call.
    // It's the equivalent of the `getPlayer` ref method in the React wrapper.
    public getPlayer(): Player | undefined {
      return this.player;
    }
  
    // This lifecycle hook runs when the component is removed from the DOM.
    ngOnDestroy(): void {
      if (this.player) {
        this.player.dispose();
      }
    }
  }
<video
  #videoPlayerElement
  [className]="className ? 'video-js ' + className : 'video-js'"
  [ngStyle]="style"
  controls
  preload="auto"
></video>
